import './globals.css'
import '../../public/styles/index.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from "next/font/local"

import {Provider} from 'react-redux'
// import store from '@/redux/store'
import { ReactNode } from 'react'
import StoreProvider from '../components/common/redux/StoreProvider/StoreProvider'
import DrawerComponent from '@/components/common/DrawerComponent/DrawerComponent'
import CartList from '@/components/common/CartList/CartList'
import Snackbar from '@/components/common/Snackbar/Snackbar'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const mollie = localFont({
  src: "../../public/fonts/mollie/mollie_glaston.ttf",
  variable: "--font-mollie"
})

// const theme = createTheme({
//   palette: {
//     primary: {main: '#000'},
//     secondary: {main: '#000'},
//     success: {main: '#10b981'}
//   }
// })

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })

export default function RootLayout({children}: {children: ReactNode}){

  return (
    <html className={`${inter.variable} ${mollie.variable}`} lang="en">
      <body className='relative overflow-x-hidden min-h-svh'>
        <StoreProvider>
          {children}
          {/* <DrawerComponent anchor='right'>
            <CartList />
          </DrawerComponent> */}
          {/* <Snackbar/> */}
        </StoreProvider>
      </body>
    </html>
  )
}
